name: CICD  

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/vars/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
     
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
           playbooks/deploy-branch-readyaml.yaml
        override-deps: |
          ansible==2.9
          ansible-lint==16.14.2
        
    - shell: bash
      env:
        auth: ${{ secrets.MERAKIAPI }}
      run: sh ./scripts/entrypoint.sh
