name: CICD  # feel free to pick your own name

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/vars/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
             
    - shell: bash
      env: meraki
        auth: ${{ secrets.AUTH }}
      run: sh ./scripts/entrypoint.sh
